### ISSUE TITLE
check if its possible to run ceph-medic vs fs snapshot

### ISSUE THREAD

**Issue by zerodayz** [ceph/ceph-medic#57]
$SUBJ

**Comment by alfredodeza** [comment]
I am not sure what you mean. Could you expand further?

**Comment by zerodayz** [comment]
can we run the ceph-medic against fs snapshot? /etc/ceph/* /var/log/ceph/* to detect possible issues with the cluster?

**Comment by alfredodeza** [comment]
what exactly does an 'fs snapshot' entail though? is it copied files? In short: no it can't.

This is basically because ceph-medic is intended to be *cluster aware*, not just look at one file in a directory. It also tries to ensure permissions and ownership are correct, these don't always correlate when copied over to another system
